apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: assignment3
type: Opaque
data:
  root-password: cm9vdHBhc3M=
  db-password: Zmxhc2twYXNz
  db-user: Zmxhc2t1c2Vy
  db-name: Zmxhc2tkYg==
